kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-schedule-scaler
subjects:
- kind: ServiceAccount
  name: k8s-schedule-scaler
roleRef:
  kind: Role
  name: k8s-schedule-scaler
  apiGroup: rbac.authorization.k8s.io
